final touches for deploy

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -11,7 +11,7 @@ jobs:
     test:
         runs-on: ubuntu-latest
         steps:
-            - name: Checkout
+            - name: Checkout Code
               uses: actions/checkout@v6
 
             - name: Set up Python
@@ -22,12 +22,11 @@ jobs:
             - name: Install dependencies
               run: |
                   python -m pip install --upgrade pip
-                  pip install -r requirements.txt
-                  pip install pytest pytest-asyncio testcontainers
+                  pip install -r requirements.txt pytest pytest-asyncio testcontainers
 
             - name: Run tests
               run: |
-                  python -m pytest tests/ -v --ignore=tests/test_database_neo4j.py
+                  python -m pytest tests/ -v
 
     deploy:
         needs: test
@@ -41,12 +40,13 @@ jobs:
             - name: Configure AWS Credentials
               uses: aws-actions/configure-aws-credentials@v6
               with:
-                  role-to-assume: arn:aws:iam::374169031176:role/GitHubActionSSMRole
-                  aws-region: ap-southeast-1
+                  role-to-assume: ${{ vars.AWS_ROLE }}
+                  aws-region: ${{ vars.AWS_REGION }}
 
             - name: Create Deployment Script
               run: |
                   cat << 'EOF' > deploy_script.sh
+                  set -e
                   cd /opt/openpecha-backend || exit 1
 
                   git fetch origin ${{ github.ref_name }}
@@ -67,11 +67,9 @@ jobs:
                   OTEL_EXPORTER_OTLP_HEADERS=${{ secrets.OTEL_EXPORTER_OTLP_HEADERS }}
                   ENV_EOF
 
-                  bash << 'APP_EOF'
                   [ -d ".venv" ] || python3 -m venv .venv
                   source .venv/bin/activate
                   pip install -r requirements.txt
-                  APP_EOF
 
                   sudo systemctl restart openpecha-api
                   EOF
@@ -89,12 +87,12 @@ jobs:
 
                   echo "Deployment started on ${{ vars.EC2_INSTANCE_ID }}. Command ID: $COMMAND_ID"
 
-                  # Wait for the command to finish. If it fails, capture the exit code.
+                  # Wait for the command to finish and capture status
                   aws ssm wait command-executed \
                     --command-id "$COMMAND_ID" \
                     --instance-id "${{ vars.EC2_INSTANCE_ID }}" || export EXIT_CODE=$?
 
-                  # If it failed, fetch and print the actual error logs from the EC2 instance
+                  # If the deployment failed, fetch the actual error logs from the EC2
                   if [ "${EXIT_CODE}" != "" ]; then
                     echo "❌ Deployment Failed. Fetching remote logs..."
                     aws ssm get-command-invocation \
